# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASER' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ASER
  pod 'Alamofire'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'NVActivityIndicatorView'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'CropViewController', '~> 2.3'
  #  pod 'FacebookShare'
  #  pod 'FacebookCore'
  #  pod 'FBSDKMessengerShareKit'
  pod 'TwitterKit'
  pod 'AFNetworking'
  pod "CZPicker"
  end
